# Exported from Render on 2026-08-27T21:27:50Z
version: "1"
projects:
  - name: CLOUDCOMPUTING
    environments:
      - name: Production
        services:
          - type: web
            name: faculty-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: faculty-service
          - type: web
            name: student-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: student-service
          - type: web
            name: eureka-server
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: eureka-server
          - type: web
            name: course-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: course-service
          - type: web
            name: attendance-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: attendance-service
          - type: web
            name: enrollment-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: enrollment-service
          - type: web
            name: api-gateway
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: api-gateway
          - type: web
            name: exam-service
            runtime: docker
            repo: https://github.com/mahes359/college-management-system
            plan: free
            envVars:
              - fromGroup: college-management-production
            region: virginia
            dockerContext: .
            dockerfilePath: ./Dockerfile
            autoDeployTrigger: commit
            rootDir: exam-service
