spring.application.name=course-service

server.port=${PORT:8083}

# MariaDB
spring.datasource.url=${COURSE_DB_URL}
spring.datasource.username=${COURSE_DB_USERNAME}
spring.datasource.password=${COURSE_DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# SOAP
spring.webservices.path=/ws

# =====================================================
# Actuator
# =====================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always